/**
 * Static option lists for fields the backend stores as free-text strings.
 * There are no ethnicity or nationality lookup endpoints in LookupController.
 */

/** KNBS census communities plus commonly listed Kalenjin, Luhya, and Mijikenda groups. */
export const KENYAN_ETHNICITIES: readonly string[] = [
  'Aweer (Boni)',
  'Bajuni',
  'Borana',
  'Bukusu',
  'Burji',
  'Chonyi',
  'Dasenach',
  'Digo',
  'Duruma',
  'El Molo',
  'Embu',
  'Gabra',
  'Giriama',
  'Gosha',
  'Idakho',
  'Isaak',
  'Isukha',
  'Jibana',
  'Kabras',
  'Kalenjin',
  'Kambe',
  'Kamba',
  'Kauma',
  'Keiyo',
  'Kenyan Arab',
  'Kenyan Asian',
  'Kenyan European',
  'Khayo',
  'Kikuyu',
  'Kipsigis',
  'Kisa',
  'Kisii',
  'Kuria',
  'Leysan',
  'Luhya',
  'Luo',
  'Maasai',
  'Marachi',
  'Maragoli',
  'Marakwet',
  'Marama',
  'Mbeere',
  'Meru',
  'Mijikenda',
  'Nandi',
  'Njemps',
  'Nubi',
  'Nyala',
  'Nyole',
  'Ogiek',
  'Orma',
  'Pokomo',
  'Pokot',
  'Rabai',
  'Rendille',
  'Ribe',
  'Sabaot',
  'Sakuye',
  'Samia',
  'Samburu',
  'Sengwer',
  'Somali',
  'Suba',
  'Swahili',
  'Tachoni',
  'Taita',
  'Taveta',
  'Terik',
  'Teso',
  'Tharaka',
  'Tiriki',
  'Tsotso',
  'Tugen',
  'Turkana',
  'Waata',
  'Wanga',
  'Other',
]

const OTHER_COUNTRIES: readonly string[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  "Côte d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]

/** UN member states and commonly listed territories. Kenya is first for this school. */
export const COUNTRIES: readonly string[] = ['Kenya', ...OTHER_COUNTRIES]

/** Keep a saved free-text value selectable after the field becomes a dropdown. */
export function withExistingOption(options: readonly string[], existing?: string | null): string[] {
  const value = existing?.trim()
  if (!value || options.includes(value)) return [...options]
  return [value, ...options]
}
