import { z } from 'zod'

/**
 * Client-side validation schemas.
 *
 * The backend performs no bean validation on these endpoints (the controllers
 * accept a raw `Map<String, String>`), so these rules exist to catch obvious
 * mistakes early and to keep users from firing pointless requests. They stay
 * deliberately permissive so they can never reject a credential the backend
 * would have accepted.
 */

export const loginSchema = z.object({
  /**
   * The backend resolves accounts with `findByUsername`, so this is a username
   * and not an email address — no email-shaped validation here.
   */
  username: z
    .string()
    .trim()
    .min(1, 'Enter your username')
    .max(150, 'That username is too long'),
  password: z.string().min(1, 'Enter your password').max(200, 'That password is too long'),
  rememberMe: z.boolean(),
})

export type LoginFormValues = z.infer<typeof loginSchema>

/** Trim first so a stray space cannot fail email validation. */
const emailField = z
  .string()
  .trim()
  .min(1, 'Enter your email address')
  .pipe(z.email('Enter a valid email address'))

export const forgotPasswordSchema = z.object({
  email: emailField,
})

export type ForgotPasswordFormValues = z.infer<typeof forgotPasswordSchema>

/** Matches the 6-digit code generated by `AuthController.forgotPassword`. */
const RESET_CODE_LENGTH = 6

export const resetPasswordSchema = z
  .object({
    email: emailField,
    code: z
      .string()
      .trim()
      .length(RESET_CODE_LENGTH, `Enter the ${RESET_CODE_LENGTH}-digit code from your email`)
      .regex(/^\d+$/, 'The code contains digits only'),
    newPassword: z
      .string()
      .min(8, 'Use at least 8 characters')
      .max(200, 'That password is too long'),
    confirmPassword: z.string().min(1, 'Confirm your new password'),
  })
  .refine((values) => values.newPassword === values.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  })

export type ResetPasswordFormValues = z.infer<typeof resetPasswordSchema>
